---
title: "Time Series Figure"
author: "Hilary Killam"
date: "07/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 999)

```


##Load Packages and Data

```{r}

library(tidyverse)
library(lubridate)
library(here)
library(readxl)
library(janitor)
library(eyetrackingR)
library(tidylog)
library(lme4)
library(ggeffects)

`%notin%` <- Negate(`%in%`)

baby_info <- read_excel(here("data", "Metadata.xlsx")) %>% clean_names() %>%
  mutate(group = case_when(group == "monolingual sp" ~ "monolingual",
                           group == "monoligual" ~ "monolingual",
                           TRUE ~ group))

exclusions <- read_excel(here("data", "Metadata.xlsx"), sheet = 2) %>% clean_names() %>%
  mutate(id = as.character(id))

aud_left <- read_csv(here("data", "auditory_left_FA.csv")) %>% clean_names() %>% 
  mutate(target_side = case_when(parse_number(trial_label) <= 12 ~ "left",
                                 TRUE ~ "right"),
         orig_file = "aud_left") %>% select(-x1)

aud_right <- read_csv(here("data", "auditory_right_FA.csv")) %>% clean_names() %>% 
  mutate(target_side = case_when(parse_number(trial_label) <= 12 ~ "right",
                                 TRUE ~ "left"),
         orig_file = "aud_right") %>% select(-x1)


#looks like trials 9 and 17 have extra data from an attention getter so have to shift time stamps for those trials
vis_left <- read_csv(here("data", "visual_left_FA.csv")) %>% clean_names() %>% 
  mutate(target_side = case_when(parse_number(trial_label) <= 12 ~ "left",
                                 TRUE ~ "right"),
         orig_file = "vis_left") %>% select(-x1, -ia_4_id) %>%
  rename(original_start_time = bin_start_time) %>%
  mutate(bin_start_time = case_when(trial_label == "Trial: 9" | trial_label == "Trial: 17" ~ original_start_time - 2110,                                   
                                           TRUE ~ original_start_time))

vis_right <- read_csv(here("data", "visual_right_FA.csv")) %>% clean_names() %>% 
  mutate(target_side = case_when(parse_number(trial_label) <= 12 ~ "right",
                                 TRUE ~ "left"),
         orig_file = "vis_right") %>% select(-x1) %>%
  mutate(original_start_time = bin_start_time) #add this column so can merge with vis_left later


##set up colours for plotting model preidctions
blues_palette <- colorRampPalette(c("#C6DBEF", "#081D58"))
blues <- blues_palette(12)
```

##Prep data
```{r}

###-----------------------------------------------------------PREPARE AUDITORY DATA

# ids_raw_aud <- aud_right %>% select(id) %>% distinct() %>% bind_rows(ids_raw)
# 
# ids_raw_aud <- ids_raw_aud %>% 
#   rename(id_raw_aud = id) %>%
#   mutate(id = id_raw_aud) %>%
#   mutate(id = str_remove(id, "ica"))  %>%
#   mutate(id = str_remove(id, "ca")) %>%
#   mutate(id = str_remove(id, "ic")) %>%
#   mutate(id = case_when(id == "524401" ~ "5244",
#                         id == "53002" ~ "5300",
#                         TRUE ~ id))
# 
# ids_raw_vis <- vis_right %>% select(id) %>% distinct() 
# ids_raw_vis <- vis_left %>% select(id) %>% distinct() %>% bind_rows(ids_raw_vis) %>% distinct()
# 
# ids_raw_vis <- ids_raw_vis %>% 
#   rename(id_raw_vis = id) %>%
#   mutate(id = id_raw_vis) %>%
#   mutate(id = str_remove(id, "icv")) %>%
#   mutate(id = str_remove(id, "ica"))
# 
# 
# ids_final <- ids %>%
#   left_join(ids_raw_aud, by = "id") %>%
#   left_join(ids_raw_vis, by = "id")
# 
# write_csv(ids_final, "kalashnikova_ids.csv")


aud_all <- aud_left %>%
  dplyr::union(aud_right) %>%
  filter(bin_start_time < 5400 & bin_start_time > 0) %>% #don't need anything after this point, since most trials have no data afterward
  mutate(id = str_remove(id, "ica"), #fix some id matching problems
         id = str_remove(id, "ic"),
         id = str_remove(id, "ca"),
         id = case_when(id == "524401" ~ "5244",
                        id == "53002" ~ "5300",
                        id == "5588a" ~ "5588",
                        TRUE ~ id),
         trial_num = parse_number(trial_label), #get trial number
         trial_type = case_when(trial_num <= 12 ~ "pre-switch",
                                TRUE ~ "post-switch"),
         trial_num = case_when(trial_num > 12 ~ trial_num - 12, #make 2 sets of 12 trials, instead of 1 to 24
                               TRUE ~ trial_num),
         trial_type = factor(trial_type, levels = c("pre-switch", "post-switch")),
         target = case_when(target_side == "left" ~ left,
                            target_side == "right" ~ right),
         distractor = case_when(target_side == "left" ~ right,
                                target_side == "right" ~ left),
         trial_name = str_c(trial_type, trial_num, sep = "_"),
         trial_unique = str_c(id, trial_name, sep = "_")) %>%
  inner_join(baby_info, by = "id")%>%
  mutate(id = as.factor(id),
         trial_num = as.numeric(trial_num),
         trial_name = as.factor(trial_name),
         group = factor(group, levels = c("monolingual", "bilingual"))) %>%
  filter(id %notin% exclusions$id)


aud_eyetracking <- aud_all %>%
  make_eyetrackingr_data(participant_column = "id",
                         trial_column = "trial_name",
                         time_column = "bin_start_time",
                         trackloss_column = "loss",
                         aoi_columns = c("target", "center", "distractor"),
                         treat_non_aoi_looks_as_missing = TRUE)

aud_full_trial <- make_time_sequence_data(aud_eyetracking,
                                         time_bin_size = 200,
                                         predictor_columns = c("group", "trial_type", "trial_num"),
                                         aois = c("center", "target", "distractor"))

aud_anticipation_window <- subset_by_window(aud_eyetracking,
                                            window_start_time = 2350,
                                            window_end_time = 3350,
                                            rezero = TRUE,
                                            remove = TRUE) %>%
  clean_by_trackloss(trial_prop_thresh = .5) %>% #remove trials that don't have at least 50% looking 
  #remove kids who don't have at least 7 out of 12 trials
  group_by(id, trial_type) %>%
  mutate(num_trials = length(unique(trial_num))) %>%
  filter(num_trials >= 7) %>%
  group_by(id) %>%
  mutate(num_trial_types = length(unique(trial_type))) %>%
  filter(num_trial_types == 2)
  

aud_final_sample_ids <- aud_anticipation_window %>%
  select(id) %>%
  distinct()

final_sample_aud_full_trial <- aud_full_trial %>%
  inner_join(aud_final_sample_ids, by = "id")

###-----------------------------------------------------------PREPARE VISUAL DATA

vis_all <- vis_left %>%
  dplyr::union(vis_right) %>%
  filter(bin_start_time > 0 & bin_start_time < 6740) %>%
  mutate(id = str_remove(id, "icv"),
         id = str_remove(id, "ica"),
         trial_num = parse_number(trial_label),
         trial_type = case_when(trial_num <= 12 ~ "pre-switch",
                                TRUE ~ "post-switch"),
         trial_num = case_when(trial_num > 12 ~ trial_num - 12,
                               TRUE ~ trial_num),
         trial_type = factor(trial_type, levels = c("pre-switch", "post-switch")),
         target = case_when(target_side == "left" ~ left,
                            target_side == "right" ~ right),
         distractor = case_when(target_side == "left" ~ right,
                                target_side == "right" ~ left),
         trial_name = str_c(trial_type, trial_num, sep = "_"),
         trial_unique = str_c(id, trial_name, sep = "_")) %>%
  filter(id != "5332") %>% #no match to this id
  left_join(baby_info, by = "id") %>%
  mutate(id = as.factor(id),
         trial_num = as.numeric(trial_num),
         trial_name = as.factor(trial_name),
         group = factor(group, levels = c("monolingual", "bilingual"))) %>%
  filter(id %notin% exclusions$id)

#check for babies missing info:

vis_all %>% select(id) %>% distinct() %>% anti_join(baby_info, by = "id")
baby_info %>% anti_join((vis_all %>% select(id) %>% distinct()), by = "id")

#two kids in eyetracking data but not info data, so remove them in script above


#----------------------------------------------RAW PLOTS FOR FIGURING OUT WEIRD STUFF
vis_all %>%
  filter(loss == 0) %>%
  group_by(bin_start_time, trial_num, trial_type, group) %>%
  summarize(target = mean(target == TRUE, na.rm = TRUE),
            distractor = mean(distractor == TRUE, na.rm = TRUE),
            center = mean(center == TRUE, na.rm = TRUE)) %>%
  pivot_longer(target:center, names_to = "aoi", values_to = "prop") %>%
  mutate(aoi = factor(aoi, levels = c("target", "distractor", "center"))) %>%
  ggplot(aes(x = bin_start_time, y = prop, color = group, linetype = aoi, alpha = aoi)) +
  geom_line() +
  facet_grid(trial_num ~ trial_type) +
  scale_alpha_manual(values = c(0.5, 0.75, 1)) 

ggsave("plot_vis_right.png")

aud_all %>%
  filter(loss == 0) %>%
  filter(!is.na(group)) %>%
  group_by(bin_start_time, trial_num, trial_type, group) %>%
  summarize(target = mean(target == TRUE, na.rm = TRUE),
            distractor = mean(distractor == TRUE, na.rm = TRUE),
            center = mean(center == TRUE, na.rm = TRUE)) %>%
  pivot_longer(target:center, names_to = "aoi", values_to = "prop") %>%
  mutate(aoi = factor(aoi, levels = c("target", "distractor", "center"))) %>%
  ggplot(aes(x = bin_start_time, y = prop, color = group, linetype = aoi, alpha = aoi)) +
  geom_line() +
  facet_grid(trial_num ~ trial_type) +
  scale_alpha_manual(values = c(0.5, 0.75, 1))

ggsave("audleft.png")

#--------------------------------------------------


vis_eyetracking <- vis_all %>%
  make_eyetrackingr_data(participant_column = "id",
                         trial_column = "trial_name",
                         time_column = "bin_start_time",
                         trackloss_column = "loss",
                         aoi_columns = c("target", "center", "distractor"),
                         treat_non_aoi_looks_as_missing = TRUE)

vis_full_trial <- make_time_sequence_data(vis_eyetracking,
                                         time_bin_size = 200,
                                         predictor_columns = c("group", "trial_type", "trial_num"),
                                         aois = c("center", "target", "distractor"))

vis_anticipation_window <- subset_by_window(vis_eyetracking,
                                            window_start_time = 3650,
                                            window_end_time = 4650,
                                            rezero = TRUE,
                                            remove = TRUE) %>%
  clean_by_trackloss(trial_prop_thresh = .5) %>% #remove trials that don't have at least 50% looking 
  #remove kids who don't have at least 7 out of 12 trials
  group_by(id, trial_type) %>%
  mutate(num_trials = length(unique(trial_num))) %>%
  filter(num_trials >= 7) %>%
  group_by(id) %>%
  mutate(num_trial_types = length(unique(trial_type))) %>%
  filter(num_trial_types == 2)
  

vis_final_sample_ids <- vis_anticipation_window %>%
  select(id) %>%
  distinct()

final_sample_vis_full_trial <- vis_full_trial %>%
  inner_join(vis_final_sample_ids, by = "id")

```

##figures

```{r}

line_colors <- c("#D55E00", "#0072B2") #c("#f77a6f", "#016abf")
line_types <- c("dotted", "solid", "dashed")
line_sizes <- c(.6, 0.5, 0.5)
facet_text_aud <- data.frame(trial_labels = c("Trial 1"), group = c("monolingual"), aoi = c("target"), Time = c(2850), trial_type_labs= c("Training", "Test"), prop_looking = c(.875), label = c("Anticipation period"))
facet_text_vis <- data.frame(trial_labels = c("Trial 1"), group = c("monolingual"), aoi = c("target"), Time = c(4150), trial_type_labs= c("Training", "Test"), prop_looking = c(.875), label = c("Anticipation period"))




###---------------------------------------------------AUDITORY


final_sample_aud_full_trial %>%
  filter(Time >= 1550 & Time <= 4150 & !is.na(group)) %>%
  mutate(trial_type_labs = case_when(trial_type == "pre-switch" ~ "Training",
                                     trial_type == "post-switch" ~ "Test"),
         group = factor(group, levels = c("monolingual", "bilingual"))) %>%
  mutate(trial_type_labs = factor(trial_type_labs, levels = c("Training", "Test"))) %>%
  pivot_wider(names_from = AOI, values_from = Prop) %>%
  group_by(trial_type_labs, group, Time, trial_num) %>%
  summarise(target = mean(target, na.rm=TRUE), 
            distractor = mean(distractor, na.rm=TRUE),
            center = mean(center, na.rm = TRUE)) %>%
  ungroup() %>%
  pivot_longer(cols = c(center, target, distractor), names_to = "aoi", values_to = "prop_looking") %>%
  mutate(aoi = factor(aoi, levels = c("center", "target", "distractor")),
         trial_labels = paste0("Trial ", trial_num),
         trial_labels = fct_reorder(trial_labels, trial_num),
         xmin = case_when(Time == 2000 & group == "monolingual" & aoi == "target" ~ 2350, #setting up the layer for the transparent rectangle showing the anticipation period
         TRUE ~ 2000),
         xmax = case_when(Time == 2000 & group == "monolingual" & aoi == "target" ~ 3350,
         TRUE ~ 2000),
         ymin = case_when(Time == 2000 & group == "monolingual" & aoi == "target" ~ Inf,
         TRUE ~ 0),
         ymax = case_when(Time == 2000 & group == "monolingual" & aoi == "target" ~ -Inf,
         TRUE ~ 0)) %>%

  ggplot(aes(x = Time, y = prop_looking, color = group, linetype = aoi)) + 
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Anticipation Period"), alpha = .1, colour = "transparent", show.legend = FALSE) +
  geom_line(aes(alpha = aoi, size = aoi)) +
  scale_color_manual(values = line_colors, guide = guide_legend(order = 1)) +
  scale_fill_manual(values = "#ffb600", labels = c("Anticipation Period"), guide = guide_legend(order = 3)) +
  scale_linetype_manual(values = line_types, labels = c("Central fixation cue", "Target", "Distractor"), guide = guide_legend(order = 2)) +
  scale_y_continuous(n.breaks = 3) +
  scale_x_continuous(breaks = c(2000, 3000, 4000)) +
  scale_alpha_manual(values = c(0.5, 0.9, 0.725), guide = "none") +
  scale_size_manual(values = line_sizes, guide = "none") +
  labs(linetype = "Area of interest",
       color = "Language group",
       fill = "Time period") +
  geom_text(data = facet_text_aud, label = facet_text_aud$label, show.legend = FALSE, color = "#666666", size = 3) +
  facet_grid(trial_labels ~ trial_type_labs) +
  # annotate("rect", xmin = 2150, xmax = 3150, ymin = -Inf, ymax = Inf, fill = "#fff000", alpha = 0.1) +
  # annotate("text", x = 2650, y = 0.875, label = "Anticipation \n Period", size = 2.75, color = "#927774") +
  ggtitle("Time course of infant looking for Auditory Study") + 
  theme_minimal(base_size = 13.5) +
  theme(plot.title = element_text(hjust = 0.5),
        strip.background = element_rect(fill = "#D9D9D9", color = "#9b9b9b"),
        panel.background = element_rect(fill = "transparent", color = "transparent"),
        panel.grid = element_line(color = "#eaeaea"),
        panel.grid.major = element_line(size = .25),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.spacing = unit(.5, "lines"),
        axis.text = element_text(size = 10)) +
  xlab("\nTime from trial start (ms)")  +
  ylab("Proportion looking\n")

ggsave("plot_full_trial_auditory.png", path = here("figures"), device = "png", width = 9, height = 11, units = "in", dpi = 300)


###---------------------------------------------------VISUAL


final_sample_vis_full_trial %>%
  filter(Time >= 2800 & Time <= 5400) %>%
  mutate(trial_type_labs = case_when(trial_type == "pre-switch" ~ "Training",
                                     trial_type == "post-switch" ~ "Test"),
         group = factor(group, levels = c("monolingual", "bilingual"))) %>%
  mutate(trial_type_labs = factor(trial_type_labs, levels = c("Training", "Test"))) %>%
  pivot_wider(names_from = AOI, values_from = Prop) %>%
  group_by(trial_type_labs, group, Time, trial_num) %>%
  summarise(target = mean(target, na.rm=TRUE), 
            distractor = mean(distractor, na.rm=TRUE),
            center = mean(center, na.rm = TRUE))  %>%
  ungroup() %>%
  pivot_longer(cols = c(center, target, distractor), names_to = "aoi", values_to = "prop_looking") %>%
  mutate(aoi = factor(aoi, levels = c("center", "target", "distractor")),
         trial_labels = paste0("Trial ", trial_num),
         trial_labels = fct_reorder(trial_labels, trial_num),
         xmin = case_when(Time == 3200 & group == "monolingual" & aoi == "target" ~ 3650, #setting up the layer for the transparent rectangle showing the original anticipation period
         TRUE ~ 3200),
         xmax = case_when(Time == 3200 & group == "monolingual" & aoi == "target" ~ 4650,
         TRUE ~ 3200),
         ymin = case_when(Time == 3200 & group == "monolingual" & aoi == "target" ~ Inf,
         TRUE ~ 0),
         ymax = case_when(Time == 3200 & group == "monolingual" & aoi == "target" ~ -Inf,
         TRUE ~ 0)) %>%
  ggplot(aes(x = Time, y = prop_looking, color = group, linetype = aoi)) + 
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Anticipation Period 1"), alpha = .1, colour = "transparent", show.legend = FALSE) +
 # geom_rect(aes(xmin = xmin2, xmax = xmax2, ymin = ymin2, ymax = ymax2, fill = "Anticipation Period 2"), alpha = .1, colour = "transparent", show.legend = FALSE) +
  geom_line(aes(alpha = aoi, size = aoi)) +
  scale_color_manual(values = line_colors, guide = guide_legend(order = 1)) +
  scale_fill_manual(values = c("#ffb600", "#556677"), labels = c("Anticipation Period 1", "Anticipation Period 2"), guide = guide_legend(order = 3)) +
  scale_linetype_manual(values = line_types, labels = c("Central fixation cue", "Target", "Distractor"), guide = guide_legend(order = 2)) +
  scale_y_continuous(n.breaks = 3) +
  scale_x_continuous(breaks = c(1000, 2000, 3000, 4000, 5000, 6000)) +
  scale_alpha_manual(values = c(0.5, 0.9, 0.725), guide = "none") +
  scale_size_manual(values = line_sizes, guide = "none") +
  labs(linetype = "Area of interest",
       color = "Language group",
       fill = "Time period") +
  geom_text(data = facet_text_vis, label = facet_text_vis$label, show.legend = FALSE, color = "#666666", size = 3) +
  facet_grid(trial_labels ~ trial_type_labs) +
  # annotate("rect", xmin = 2150, xmax = 3150, ymin = -Inf, ymax = Inf, fill = "#fff000", alpha = 0.1) +
  # annotate("text", x = 2650, y = 0.875, label = "Anticipation \n Period", size = 2.75, color = "#927774") +
  ggtitle("Time course of infant looking for Visual Study") + 
  theme_minimal(base_size = 13.5) +
  theme(plot.title = element_text(hjust = 0.5),
        strip.background = element_rect(fill = "#D9D9D9", color = "#9b9b9b"),
        panel.background = element_rect(fill = "transparent", color = "transparent"),
        panel.grid = element_line(color = "#eaeaea"),
        panel.grid.major = element_line(size = .25),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.spacing = unit(.5, "lines"),
        axis.text = element_text(size = 10)) +
  xlab("\nTime from trial start (ms)")  +
  ylab("Proportion looking\n")

ggsave("plot_full_trial_visual.png", path = here("figures"), device = "png", width = 9, height = 11, units = "in", dpi = 300)

```


##Models

```{r}

##------------------------------------AUDITORY

aud_model_data <- make_time_sequence_data(aud_anticipation_window,
                                         time_bin_size = 200,
                                         predictor_columns = c("group", "trial_type", "trial_num", "task_order"),
                                         aois = c("center", "target", "distractor")) %>%
  filter(AOI == "target") %>%
  filter(trial_num != 1) %>%
  mutate(trial_num_scaled = trial_num - 2,
         trial_num_halved = trial_num_scaled/2,
         trial_num_centred = trial_num - 7) 

aud_model_data_pre <- aud_model_data %>%
  filter(trial_type == "pre-switch")

aud_model_data_post <-  aud_model_data %>%
  filter(trial_type == "post-switch") 




aud_model_pre <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_halved + (1 | id), data = aud_model_data_pre, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))

summary(aud_model_pre)

aud_model_pre2 <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_scaled + (1 | id), data = aud_model_data_pre, family = binomial, weights = SamplesTotal, control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))

summary(aud_model_pre2)

allFit(show.meth.tab = TRUE)
allFit(aud_model_pre2)

tt <- getME(aud_model_pre2,"theta")
ll <- getME(aud_model_pre2,"lower")
min(tt[ll==0])



aud_model_post <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_halved + (1 | id), data = aud_model_data_post, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000))) 

summary(aud_model_post)




##------------------------------------VISUAL

vis_model_data <- make_time_sequence_data(vis_anticipation_window,
                                         time_bin_size = 200,
                                         predictor_columns = c("group", "trial_type", "trial_num", "task_order"),
                                         aois = c("center", "target", "distractor")) %>%
  filter(AOI == "target") %>%
  filter(trial_num != 1) %>%
  mutate(trial_num_scaled = trial_num - 2,
         trial_num_halved = trial_num_scaled/2,
         trial_num_centred = trial_num - 7) 

vis_model_data_pre <- vis_model_data %>%
  filter(trial_type == "pre-switch")

vis_model_data_post <-  vis_model_data %>%
  filter(trial_type == "post-switch") 




vis_model_pre <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_halved + (1 | id), data = vis_model_data_pre, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))

summary(vis_model_pre)


vis_model_post <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_halved + (1 | id), data = vis_model_data_post, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000))) 

summary(vis_model_post)

```
##Plot model predicted values

```{r}

##-----------------------------------AUDITORY

ggpredict(aud_model_pre, terms = c("TimeBin", "trial_num_halved [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]", "group"), type = "fe", ci.lvl = FALSE) %>% plot(colors = "trial_num_halved", line.size = 1, connect.lines = TRUE) +
  labs(title = "Predicted values of proportion looking to target during the Training phase \nin Experiment 1c (Auditory condition)", x = "Time in milliseconds during anticipation period", y = "Proportion looking to target", color = "Trial number") +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  scale_x_continuous(breaks = c(0, 2, 4), labels = c("0", "500", "1000")) +
  ylim(-0.1, 1) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))

ggpredict(aud_model_post, terms = c("TimeBin", "trial_num_halved [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]", "group"), type = "fe", ci.lvl = FALSE) %>% plot(colors = "trial_num_halved", line.size = 1, connect.lines = TRUE) +
  labs(title = "Predicted values of proportion looking to target during the Test phase \nin Experiment 1c (Auditory condition)", x = "Time in milliseconds during anticipation period", y = "Proportion looking to target", color = "Trial number") +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  scale_x_continuous(breaks = c(0, 2, 4), labels = c("0", "500", "1000")) +
  ylim(-0.1, 1) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))


##-----------------------------------VISUAL

ggpredict(vis_model_pre, terms = c("TimeBin", "trial_num_halved [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]", "group"), type = "fe", ci.lvl = FALSE) %>% plot(colors = "trial_num_halved", line.size = 1, connect.lines = TRUE) +
  labs(title = "Predicted values of proportion looking to target during the Training phase \nin Experiment 1c (Visual condition)", x = "Time in milliseconds during anticipation period", y = "Proportion looking to target", color = "Trial number") +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  scale_x_continuous(breaks = c(0, 2, 4), labels = c("0", "500", "1000")) +
  ylim(-0.1, 1) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))

ggpredict(vis_model_post, terms = c("TimeBin", "trial_num_halved [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]", "group"), type = "fe", ci.lvl = FALSE) %>% plot(colors = "trial_num_halved", line.size = 1, connect.lines = TRUE) +
  labs(title = "Predicted values of proportion looking to target during the Test phase \nin Experiment 1c (Visual condition)", x = "Time in milliseconds during anticipation period", y = "Proportion looking to target", color = "Trial number") +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  scale_x_continuous(breaks = c(0, 2, 4), labels = c("0", "500", "1000")) +
  ylim(-0.1, 1) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))
```



##Merge data frames

```{r}
aud_all %>%

  group_by(bin_start_time, trial_num, trial_type, group) %>%
  mutate(target_prop = mean(target == "TRUE"),
         distractor_prop = mean(distractor == "TRUE"),
         centre_prop = mean(center == "TRUE"),
         total_prop = (left_prop + right_prop + centre_prop)) %>%
  pivot_longer(left_prop:total_prop, names_to = "side", values_to = "prop") %>%
  ggplot(aes(x = bin_start_time, y = prop, color = side)) +
  geom_line() +
  scale_y_continuous(limits = c(0, 1)) +
  facet_grid(trial_num ~ trial_type)
  
vis_all %>%
  
  filter(!is.na(group)) %>%
  group_by(bin_start_time, trial_num, trial_type, group) %>%
  mutate(target_prop = mean(target == "TRUE"),
         distractor_prop = mean(distractor == "TRUE"),
         centre_prop = mean(center == "TRUE")) %>%
  pivot_longer(target_prop:centre_prop, names_to = "side", values_to = "prop") %>%
  ggplot(aes(x = bin_start_time, y = prop, color = group, linetype = side)) +
  geom_line() +
  scale_y_continuous(limits = c(0, 1)) +
  facet_grid(trial_num ~ trial_type)

ggsave("plot.png")

  
  

final_sample_vis_full_trial %>%
  filter(Time >= 1550 & Time <= 4150 & !is.na(group) & trial_num == 1) %>%
  ggplot(aes(x = Time, y = Prop, linetype = AOI, color = group)) +
  geom_smooth(se= FALSE) +
  facet_wrap( ~ trial_type)

final_sample_aud_full_trial %>%
  filter(Time >= 1550 & Time <= 4150 & !is.na(group) & trial_num == 1) %>%
  ggplot(aes(x = Time, y = Prop, linetype = AOI, color = group)) +
  geom_smooth(se= FALSE) +
  facet_wrap( ~ trial_type)

  
aud_model_data %>%
  ggplot(aes(x = TimeBin, y = Prop, color = group)) +
  geom_smooth(se = FALSE) +
  facet_grid(trial_type ~ trial_num)

vis_all %>% mutate(message2 = case_when(is.na(parse_number(message)) ~ message, TRUE ~ NA_character_)) %>% select(message2, bin_start_time) %>% filter(!is.na(message2)) %>% distinct()

```



