---
title: "Time Series Figure"
author: "Hilary Killam"
date: "07/07/2020"
output: html_document
---
##Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 999)

library(tidyverse)
library(lubridate)
library(here)
library(readxl)
library(janitor)
library(eyetrackingR)
library(tidylog)
library(lme4)
library(ggeffects)
library(apaTables)
library(sjPlot)

`%notin%` <- Negate(`%in%`)

```


##Load Data
```{r}

baby_info <- read_excel(here("data", "Metadata.xlsx")) %>% clean_names() %>%
  mutate(group = case_when(group == "monolingual sp" ~ "monolingual",
                           group == "monoligual" ~ "monolingual",
                           TRUE ~ group),
         visual_tl = case_when(id == "5314" ~ auditory_tl, #looks like this kid had a mistake in the baby info sheet... they have data for auditory trackloss but no data for visual trackloss, yet they only participated in the visual session. I double checked the trackloss number for the visual session, and it matches what was put under auditory, so I think they should be swapped.
                               TRUE ~ visual_tl),
         auditory_tl = case_when(id == "5314" ~ visual_tl,
                                 TRUE ~ auditory_tl)) 

exclusions <- read_excel(here("data", "Metadata.xlsx"), sheet = 2) %>% clean_names() %>%
  mutate(id = as.character(id))

aud_left <- read_csv(here("data", "auditory_left_FA.csv")) %>% clean_names() %>% 
  mutate(target_side = case_when(parse_number(trial_label) <= 12 ~ "left",
                                 TRUE ~ "right"),
         orig_file = "aud_left") %>% select(-x1)

aud_right <- read_csv(here("data", "auditory_right_FA.csv")) %>% clean_names() %>% 
  mutate(target_side = case_when(parse_number(trial_label) <= 12 ~ "right",
                                 TRUE ~ "left"),
         orig_file = "aud_right") %>% select(-x1)


#looks like trials 9 and 17 have extra data from an attention getter so have to shift time stamps for those trials
vis_left <- read_csv(here("data", "visual_left_FA.csv")) %>% clean_names() %>% 
  mutate(target_side = case_when(parse_number(trial_label) <= 12 ~ "left",
                                 TRUE ~ "right"),
         orig_file = "vis_left") %>% select(-x1, -ia_4_id) %>%
  rename(original_start_time = bin_start_time) %>%
  mutate(bin_start_time = case_when(trial_label == "Trial: 9" | trial_label == "Trial: 17" ~ original_start_time - 2110,                                   
                                           TRUE ~ original_start_time))

vis_right <- read_csv(here("data", "visual_right_FA.csv")) %>% clean_names() %>% 
  mutate(target_side = case_when(parse_number(trial_label) <= 12 ~ "right",
                                 TRUE ~ "left"),
         orig_file = "vis_right") %>% select(-x1) %>%
  mutate(original_start_time = bin_start_time) #add this column so can merge with vis_left later


##set up colours for plotting model preidctions
blues_palette <- colorRampPalette(c("#C6DBEF", "#081D58"))
blues <- blues_palette(12)


```
#Analysis with our exclusion criteria

##Prep data
```{r}
###-----------------------------commented script was to investigate IDs that were not matching up

# ids_raw_aud <- aud_right %>% select(id) %>% distinct() %>% bind_rows(ids_raw)
# 
# ids_raw_aud <- ids_raw_aud %>% 
#   rename(id_raw_aud = id) %>%
#   mutate(id = id_raw_aud) %>%
#   mutate(id = str_remove(id, "ica"))  %>%
#   mutate(id = str_remove(id, "ca")) %>%
#   mutate(id = str_remove(id, "ic")) %>%
#   mutate(id = case_when(id == "524401" ~ "5244",
#                         id == "53002" ~ "5300",
#                         TRUE ~ id))
# 
# ids_raw_vis <- vis_right %>% select(id) %>% distinct() 
# ids_raw_vis <- vis_left %>% select(id) %>% distinct() %>% bind_rows(ids_raw_vis) %>% distinct()
# 
# ids_raw_vis <- ids_raw_vis %>% 
#   rename(id_raw_vis = id) %>%
#   mutate(id = id_raw_vis) %>%
#   mutate(id = str_remove(id, "icv")) %>%
#   mutate(id = str_remove(id, "ica"))
# 
# 
# ids_final <- ids %>%
#   left_join(ids_raw_aud, by = "id") %>%
#   left_join(ids_raw_vis, by = "id")
# 
# write_csv(ids_final, "kalashnikova_ids.csv")

###-----------------------------------------------------------PREPARE AUDITORY DATA


aud_all <- aud_left %>%
  dplyr::union(aud_right) %>% #merge left and right dataframes
  filter(bin_start_time < 5400 & bin_start_time > 0) %>% #don't need anything after this point, since most trials have no data afterward except one weird one 
  mutate(id = str_remove(id, "ica"), #fix some id matching problems
         id = str_remove(id, "ic"),
         id = str_remove(id, "ca"),
         id = case_when(id == "524401" ~ "5244",
                        id == "53002" ~ "5300",
                        id == "5588a" ~ "5588",
                        TRUE ~ id),
         trial_num = parse_number(trial_label), #get trial number
         trial_type = case_when(trial_num <= 12 ~ "pre-switch",
                                TRUE ~ "post-switch"),
         trial_num = case_when(trial_num > 12 ~ trial_num - 12, #make 2 sets of 12 trials, instead of 1 to 24
                               TRUE ~ trial_num),
         trial_type = factor(trial_type, levels = c("pre-switch", "post-switch")),
         target = case_when(target_side == "left" ~ left, #set AOI columns
                            target_side == "right" ~ right),
         distractor = case_when(target_side == "left" ~ right,
                                target_side == "right" ~ left),
         trial_name = str_c(trial_type, trial_num, sep = "_"),
         trial_unique = str_c(id, trial_name, sep = "_")) %>%
  inner_join(baby_info, by = "id") %>% #merge with participant info
  mutate(id = as.factor(id),
         trial_num = as.numeric(trial_num),
         trial_name = as.factor(trial_name),
         group = factor(group, levels = c("monolingual", "bilingual"))) %>%
  filter(id %notin% exclusions$id) #get rid of any kids that match an ID in the exclusions file

##-------------------------------------------------------MAKE AUDITORY EYETRACKING DATA
aud_eyetracking <- aud_all %>%
  make_eyetrackingr_data(participant_column = "id",
                         trial_column = "trial_name",
                         time_column = "bin_start_time",
                         trackloss_column = "loss",
                         aoi_columns = c("target", "center", "distractor"),
                         treat_non_aoi_looks_as_missing = TRUE)

aud_full_trial <- make_time_sequence_data(aud_eyetracking,
                                         time_bin_size = 200,
                                         predictor_columns = c("group", "trial_type", "trial_num"),
                                         aois = c("center", "target", "distractor"))

aud_anticipation_window <- subset_by_window(aud_eyetracking,
                                            window_start_time = 2350,
                                            window_end_time = 3350,
                                            rezero = TRUE,
                                            remove = TRUE) %>%
  clean_by_trackloss(trial_prop_thresh = .5) %>% #remove trials that don't have at least 50% looking 
  #remove kids who don't have at least 7 out of 12 trials
  group_by(id, trial_type) %>%
  mutate(num_trials = length(unique(trial_num))) %>%
  filter(num_trials >= 7) %>%
  group_by(id) %>%
  mutate(num_trial_types = length(unique(trial_type))) %>%
  filter(num_trial_types == 2)
  

aud_final_sample_ids <- aud_anticipation_window %>%
  select(id) %>%
  distinct()

final_sample_aud_full_trial <- aud_full_trial %>%
  inner_join(aud_final_sample_ids, by = "id")

full_sample_aud_full_trial <- aud_eyetracking %>%
  filter(auditory_tl <= 0.6) %>%
  make_time_sequence_data(time_bin_size = 200,
                          predictor_columns = c("group", "trial_type", "trial_num"),
                          aois = c("center", "target", "distractor"))

full_sample_aud_anticipation_window <- aud_eyetracking %>%
  filter(auditory_tl <= 0.6) %>% #Kalashnikova's original trackloss threshold
  subset_by_window(window_start_time = 2350,
                                            window_end_time = 3350,
                                            rezero = TRUE,
                                            remove = TRUE) 

###-----------------------------------------------------------PREPARE VISUAL DATA

vis_all <- vis_left %>%
  dplyr::union(vis_right) %>%
  filter(bin_start_time > 0 & bin_start_time < 6740) %>%
  mutate(id = str_remove(id, "icv"),
         id = str_remove(id, "ica"),
         id = case_when(str_detect(id, "5332") ~ "5532", #typo in eyetracking ID
                        TRUE ~ id),
         trial_num = parse_number(trial_label),
         trial_type = case_when(trial_num <= 12 ~ "pre-switch",
                                TRUE ~ "post-switch"),
         trial_num = case_when(trial_num > 12 ~ trial_num - 12,
                               TRUE ~ trial_num),
         trial_type = factor(trial_type, levels = c("pre-switch", "post-switch")),
         target = case_when(target_side == "left" ~ left,
                            target_side == "right" ~ right),
         distractor = case_when(target_side == "left" ~ right,
                                target_side == "right" ~ left),
         trial_name = str_c(trial_type, trial_num, sep = "_"),
         trial_unique = str_c(id, trial_name, sep = "_")) %>%
  inner_join(baby_info, by = "id") %>%
  mutate(id = as.factor(id),
         trial_num = as.numeric(trial_num),
         trial_name = as.factor(trial_name),
         group = factor(group, levels = c("monolingual", "bilingual"))) %>%
  filter(id %notin% exclusions$id)

#check for babies missing info:

vis_all %>% select(id) %>% distinct() %>% anti_join(baby_info, by = "id")
baby_info %>% anti_join((vis_all %>% select(id) %>% distinct()), by = "id")

#two kids in eyetracking data but not info data


#----------------------------------------------RAW PLOTS FOR FIGURING OUT WEIRD STUFF
# vis_all %>%
#   filter(loss == 0) %>%
#   group_by(bin_start_time, trial_num, trial_type, group) %>%
#   summarize(target = mean(target == TRUE, na.rm = TRUE),
#             distractor = mean(distractor == TRUE, na.rm = TRUE),
#             center = mean(center == TRUE, na.rm = TRUE)) %>%
#   pivot_longer(target:center, names_to = "aoi", values_to = "prop") %>%
#   mutate(aoi = factor(aoi, levels = c("target", "distractor", "center"))) %>%
#   ggplot(aes(x = bin_start_time, y = prop, color = group, linetype = aoi, alpha = aoi)) +
#   geom_line() +
#   facet_grid(trial_num ~ trial_type) +
#   scale_alpha_manual(values = c(0.5, 0.75, 1)) 
# 
# #ggsave("plot_vis_right.png")
# 
# aud_all %>%
#   filter(loss == 0) %>%
#   filter(!is.na(group)) %>%
#   group_by(bin_start_time, trial_num, trial_type, group) %>%
#   summarize(target = mean(target == TRUE, na.rm = TRUE),
#             distractor = mean(distractor == TRUE, na.rm = TRUE),
#             center = mean(center == TRUE, na.rm = TRUE)) %>%
#   pivot_longer(target:center, names_to = "aoi", values_to = "prop") %>%
#   mutate(aoi = factor(aoi, levels = c("target", "distractor", "center"))) %>%
#   ggplot(aes(x = bin_start_time, y = prop, color = group, linetype = aoi, alpha = aoi)) +
#   geom_line() +
#   facet_grid(trial_num ~ trial_type) +
#   scale_alpha_manual(values = c(0.5, 0.75, 1))
# 
# #ggsave("audleft.png")



vis_eyetracking <- vis_all %>%
  make_eyetrackingr_data(participant_column = "id",
                         trial_column = "trial_name",
                         time_column = "bin_start_time",
                         trackloss_column = "loss",
                         aoi_columns = c("target", "center", "distractor"),
                         treat_non_aoi_looks_as_missing = TRUE)

vis_full_trial <- make_time_sequence_data(vis_eyetracking,
                                         time_bin_size = 200,
                                         predictor_columns = c("group", "trial_type", "trial_num"),
                                         aois = c("center", "target", "distractor"))

vis_anticipation_window <- subset_by_window(vis_eyetracking,
                                            window_start_time = 3650,
                                            window_end_time = 4650,
                                            rezero = TRUE,
                                            remove = TRUE) %>%
  clean_by_trackloss(trial_prop_thresh = .5) %>% #remove trials that don't have at least 50% looking 
  #remove kids who don't have at least 7 out of 12 trials
  group_by(id, trial_type) %>%
  mutate(num_trials = length(unique(trial_num))) %>%
  filter(num_trials >= 7) %>%
  group_by(id) %>%
  mutate(num_trial_types = length(unique(trial_type))) %>%
  filter(num_trial_types == 2)
  

vis_final_sample_ids <- vis_anticipation_window %>%
  select(id) %>%
  distinct()

final_sample_vis_full_trial <- vis_full_trial %>%
  inner_join(vis_final_sample_ids, by = "id")

full_sample_vis_full_trial <- vis_eyetracking %>%
  filter(visual_tl <= 0.6) %>%
  make_time_sequence_data(time_bin_size = 200,
                          predictor_columns = c("group", "trial_type", "trial_num"),
                          aois = c("center", "target", "distractor"))

full_sample_vis_anticipation_window <- vis_eyetracking %>%
  filter(visual_tl <= 0.6) %>% #Kalashnikova's original trackloss threshold
  subset_by_window(window_start_time = 3650,
                                            window_end_time = 4650,
                                            rezero = TRUE,
                                            remove = TRUE) 

```

##Descriptives

```{r}
#language group counts per condition in final sample

final_sample_aud_full_trial %>%
  select(id, group) %>%
  distinct() %>%
  count(group)

final_sample_vis_full_trial %>%
  select(id, group) %>%
  distinct() %>%
  count(group)

#language group counts per condition in full sample

full_sample_aud_full_trial %>%
  select(id, group) %>%
  distinct() %>%
  count(group)

full_sample_vis_full_trial  %>%
  select(id, group) %>%
  distinct() %>%
  count(group)

```


##Time series plots

```{r}

line_colors <- c("#D55E00", "#0072B2") #c("#f77a6f", "#016abf")
line_types <- c("dotted", "solid", "dashed")
line_sizes <- c(.6, 0.5, 0.5)
facet_text_aud <- data.frame(trial_labels = c("Trial 1"), group = c("monolingual"), aoi = c("target"), Time = c(2850), trial_type_labs= c("Training", "Test"), prop_looking = c(.875), label = c("Anticipation period"))
facet_text_vis <- data.frame(trial_labels = c("Trial 1"), group = c("monolingual"), aoi = c("target"), Time = c(4150), trial_type_labs= c("Training", "Test"), prop_looking = c(.875), label = c("Anticipation period"))



###---------------------------------------------------AUDITORY (using anticipation period 2350-3350 ms)


final_sample_aud_full_trial %>%
  filter(Time >= 1550 & Time <= 4150 & !is.na(group)) %>% #truncate timeline for plots
  mutate(trial_type_labs = case_when(trial_type == "pre-switch" ~ "Training",
                                     trial_type == "post-switch" ~ "Test"),
         group = factor(group, levels = c("monolingual", "bilingual"))) %>%
  mutate(trial_type_labs = factor(trial_type_labs, levels = c("Training", "Test"))) %>%
  pivot_wider(names_from = AOI, values_from = Prop) %>%
  group_by(trial_type_labs, group, Time, trial_num) %>%
  summarise(target = mean(target, na.rm=TRUE), 
            distractor = mean(distractor, na.rm=TRUE),
            center = mean(center, na.rm = TRUE)) %>%
  ungroup() %>%
  pivot_longer(cols = c(center, target, distractor), names_to = "aoi", values_to = "prop_looking") %>%
  mutate(aoi = factor(aoi, levels = c("center", "target", "distractor")),
         trial_labels = paste0("Trial ", trial_num),
         trial_labels = fct_reorder(trial_labels, trial_num),
         xmin = case_when(Time == 2000 & group == "monolingual" & aoi == "target" ~ 2350, #setting up the layer for the transparent rectangle showing the anticipation period
         TRUE ~ 2000),
         xmax = case_when(Time == 2000 & group == "monolingual" & aoi == "target" ~ 3350,
         TRUE ~ 2000),
         ymin = case_when(Time == 2000 & group == "monolingual" & aoi == "target" ~ Inf,
         TRUE ~ 0),
         ymax = case_when(Time == 2000 & group == "monolingual" & aoi == "target" ~ -Inf,
         TRUE ~ 0)) %>%

  ggplot(aes(x = Time, y = prop_looking, color = group, linetype = aoi)) + 
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Anticipation Period"), alpha = .1, colour = "transparent", show.legend = FALSE) +
  geom_line(aes(alpha = aoi, size = aoi)) +
  scale_color_manual(values = line_colors, guide = guide_legend(order = 1)) +
  scale_fill_manual(values = "#ffb600", labels = c("Anticipation Period"), guide = guide_legend(order = 3)) +
  scale_linetype_manual(values = line_types, labels = c("Central fixation cue", "Target", "Distractor"), guide = guide_legend(order = 2)) +
  scale_y_continuous(n.breaks = 3) +
  scale_x_continuous(breaks = c(2000, 3000, 4000)) +
  scale_alpha_manual(values = c(0.5, 0.9, 0.725), guide = "none") +
  scale_size_manual(values = line_sizes, guide = "none") +
  labs(linetype = "Area of interest",
       color = "Language group",
       fill = "Time period") +
  geom_text(data = facet_text_aud, label = facet_text_aud$label, show.legend = FALSE, color = "#666666", size = 3) +
  facet_grid(trial_labels ~ trial_type_labs) +
  # annotate("rect", xmin = 2150, xmax = 3150, ymin = -Inf, ymax = Inf, fill = "#fff000", alpha = 0.1) +
  # annotate("text", x = 2650, y = 0.875, label = "Anticipation \n Period", size = 2.75, color = "#927774") +
  ggtitle("Time course of infant looking for Study 1c (auditory condition)") + 
  theme_minimal(base_size = 13.5) +
  theme(plot.title = element_text(hjust = 0.5),
        strip.background = element_rect(fill = "#D9D9D9", color = "#9b9b9b"),
        panel.background = element_rect(fill = "transparent", color = "transparent"),
        panel.grid = element_line(color = "#eaeaea"),
        panel.grid.major = element_line(size = .25),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.spacing = unit(.5, "lines"),
        axis.text = element_text(size = 10)) +
  xlab("\nTime from trial start (ms)")  +
  ylab("Proportion looking\n")

#ggsave("plot_full_trial_auditory.png", path = here("figures"), device = "png", width = 9, height = 11, units = "in", dpi = 300)


###---------------------------------------------------VISUAL (using anticipation period 3650 - 4650)


final_sample_vis_full_trial %>%
  filter(Time >= 2800 & Time <= 5400) %>%
  mutate(trial_type_labs = case_when(trial_type == "pre-switch" ~ "Training",
                                     trial_type == "post-switch" ~ "Test"),
         group = factor(group, levels = c("monolingual", "bilingual"))) %>%
  mutate(trial_type_labs = factor(trial_type_labs, levels = c("Training", "Test"))) %>%
  pivot_wider(names_from = AOI, values_from = Prop) %>%
  group_by(trial_type_labs, group, Time, trial_num) %>%
  summarise(target = mean(target, na.rm=TRUE), 
            distractor = mean(distractor, na.rm=TRUE),
            center = mean(center, na.rm = TRUE))  %>%
  ungroup() %>%
  pivot_longer(cols = c(center, target, distractor), names_to = "aoi", values_to = "prop_looking") %>%
  mutate(aoi = factor(aoi, levels = c("center", "target", "distractor")),
         trial_labels = paste0("Trial ", trial_num),
         trial_labels = fct_reorder(trial_labels, trial_num),
         xmin = case_when(Time == 3200 & group == "monolingual" & aoi == "target" ~ 3650, #setting up the layer for the transparent rectangle showing the original anticipation period
         TRUE ~ 3200),
         xmax = case_when(Time == 3200 & group == "monolingual" & aoi == "target" ~ 4650,
         TRUE ~ 3200),
         ymin = case_when(Time == 3200 & group == "monolingual" & aoi == "target" ~ Inf,
         TRUE ~ 0),
         ymax = case_when(Time == 3200 & group == "monolingual" & aoi == "target" ~ -Inf,
         TRUE ~ 0)) %>%
  ggplot(aes(x = Time, y = prop_looking, color = group, linetype = aoi)) + 
  geom_rect(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "Anticipation Period 1"), alpha = .1, colour = "transparent", show.legend = FALSE) +
 # geom_rect(aes(xmin = xmin2, xmax = xmax2, ymin = ymin2, ymax = ymax2, fill = "Anticipation Period 2"), alpha = .1, colour = "transparent", show.legend = FALSE) +
  geom_line(aes(alpha = aoi, size = aoi)) +
  scale_color_manual(values = line_colors, guide = guide_legend(order = 1)) +
  scale_fill_manual(values = c("#ffb600", "#556677"), labels = c("Anticipation Period 1", "Anticipation Period 2"), guide = guide_legend(order = 3)) +
  scale_linetype_manual(values = line_types, labels = c("Central fixation cue", "Target", "Distractor"), guide = guide_legend(order = 2)) +
  scale_y_continuous(n.breaks = 3) +
  scale_x_continuous(breaks = c(1000, 2000, 3000, 4000, 5000, 6000)) +
  scale_alpha_manual(values = c(0.5, 0.9, 0.725), guide = "none") +
  scale_size_manual(values = line_sizes, guide = "none") +
  labs(linetype = "Area of interest",
       color = "Language group",
       fill = "Time period") +
  geom_text(data = facet_text_vis, label = facet_text_vis$label, show.legend = FALSE, color = "#666666", size = 3) +
  facet_grid(trial_labels ~ trial_type_labs) +
  # annotate("rect", xmin = 2150, xmax = 3150, ymin = -Inf, ymax = Inf, fill = "#fff000", alpha = 0.1) +
  # annotate("text", x = 2650, y = 0.875, label = "Anticipation \n Period", size = 2.75, color = "#927774") +
  ggtitle("Time course of infant looking for Study 1c (visual condition)") + 
  theme_minimal(base_size = 13.5) +
  theme(plot.title = element_text(hjust = 0.5),
        strip.background = element_rect(fill = "#D9D9D9", color = "#9b9b9b"),
        panel.background = element_rect(fill = "transparent", color = "transparent"),
        panel.grid = element_line(color = "#eaeaea"),
        panel.grid.major = element_line(size = .25),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.spacing = unit(.5, "lines"),
        axis.text = element_text(size = 10)) +
  xlab("\nTime from trial start (ms)")  +
  ylab("Proportion looking\n")

#ggsave("plot_full_trial_visual.png", path = here("figures"), device = "png", width = 9, height = 11, units = "in", dpi = 300)

```


##Models

```{r}

##------------------------------------AUDITORY

aud_model_data <- make_time_sequence_data(aud_anticipation_window,
                                         time_bin_size = 200,
                                         predictor_columns = c("group", "trial_type", "trial_num", "task_order"),
                                         aois = c("center", "target", "distractor")) %>%
  filter(AOI == "target") %>%
  filter(trial_num != 1) %>%
  mutate(trial_num_scaled = trial_num - 2,
         trial_num_halved = trial_num_scaled/2,
         trial_num_centred = trial_num - 7) 

aud_model_data_pre <- aud_model_data %>%
  filter(trial_type == "pre-switch")

aud_model_data_post <-  aud_model_data %>%
  filter(trial_type == "post-switch") 

##### Problems converging models without rescaling trial number, so estimates end up being doubled when scaling trial number to half the size. Model estimates for unscaled trial number seem to be the same as for the scaled one (though any effects that include trial number are halved), but have a warning. Models converge without rescaling if only 8 trials are included (trials 2-9 like in the CogControl analysis). I believe the warning is a false positive, but I cannot get them to converge even by changing the optimizer or maximum attempts allowed.


aud_model_pre <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_scaled + (1 | id), data = aud_model_data_pre, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))

summary(aud_model_pre)

aud_model_pre2 <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_halved + (1 | id), data = aud_model_data_pre, family = binomial, weights = SamplesTotal, control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000))) #convergence problems with unscaled trial number & also with centred trial number

summary(aud_model_pre2)


##----------------------------------check if unscaled models will converge with other optimizers. Short answer: No. But, testing for true failure of convergence doesn't seem like there's a problem... the tt and ll code below is nowhere close to 0. So I think the regular model should be fine to report.

# allFit(show.meth.tab = TRUE)
# allFit(aud_model_pre)
# 
# tt <- getME(aud_model_pre,"theta")
# ll <- getME(aud_model_pre,"lower")
# min(tt[ll==0])



aud_model_post <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_scaled + (1 | id), data = aud_model_data_post, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000))) 

summary(aud_model_post)

aud_model_post2 <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_halved + (1 | id), data = aud_model_data_post, family = binomial, weights = SamplesTotal, control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000))) #convergence problems with unscaled trial number & also with centred trial number

summary(aud_model_post2)


##------------------------------------VISUAL

vis_model_data <- make_time_sequence_data(vis_anticipation_window,
                                         time_bin_size = 200,
                                         predictor_columns = c("group", "trial_type", "trial_num", "task_order"),
                                         aois = c("center", "target", "distractor")) %>%
  filter(AOI == "target") %>%
  filter(trial_num != 1) %>%
  mutate(trial_num_scaled = trial_num - 2,
         trial_num_halved = trial_num_scaled/2,
         trial_num_centred = trial_num - 7) 

vis_model_data_pre <- vis_model_data %>%
  filter(trial_type == "pre-switch")

vis_model_data_post <-  vis_model_data %>%
  filter(trial_type == "post-switch") 


###Same convergence problems in visual dataset, only works with halved trial number but the estimates seem the same as for the unscaled variable (though doubled estimates for effects including trial number)

vis_model_pre <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_scaled + (1 | id), data = vis_model_data_pre, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))

summary(vis_model_pre)

vis_model_pre2 <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_halved + (1 | id), data = vis_model_data_pre, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))

summary(vis_model_pre2)


vis_model_post <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_scaled + (1 | id), data = vis_model_data_post, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000))) 

summary(vis_model_post)

vis_model_post2 <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_halved + (1 | id), data = vis_model_data_post, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000))) 

summary(vis_model_post2)


###----------------------------------------------------MODEL RESULTS TABLES

tab_model(aud_model_pre, show.re.var = FALSE, show.icc = FALSE)
tab_model(aud_model_post, show.re.var = FALSE, show.icc = FALSE)
tab_model(vis_model_pre, show.re.var = FALSE, show.icc = FALSE)
tab_model(vis_model_post, show.re.var = FALSE, show.icc = FALSE)


```


##Flipped language level models (to see Bilingual baseline effects) - only using the unscaled trial number variable 

```{r}

##------------------------------------AUDITORY

aud_model_data_pre_flipped <- aud_model_data %>%
  filter(trial_type == "pre-switch") %>%
  mutate(group = factor(group, levels = c("bilingual", "monolingual")))

aud_model_data_post_flipped <-  aud_model_data %>%
  filter(trial_type == "post-switch") %>%
  mutate(group = factor(group, levels = c("bilingual", "monolingual")))


aud_model_pre_flipped <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_scaled + (1 | id), data = aud_model_data_pre_flipped, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))

summary(aud_model_pre_flipped)

aud_model_post_flipped <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_scaled + (1 | id), data = aud_model_data_post_flipped, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000))) 

summary(aud_model_post_flipped)

##------------------------------------VISUAL

vis_model_data_pre_flipped <- vis_model_data %>%
  filter(trial_type == "pre-switch") %>%
  mutate(group = factor(group, levels = c("bilingual", "monolingual")))

vis_model_data_post_flipped <-  vis_model_data %>%
  filter(trial_type == "post-switch") %>%
  mutate(group = factor(group, levels = c("bilingual", "monolingual")))

vis_model_pre_flipped <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_scaled + (1 | id), data = vis_model_data_pre_flipped, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))

summary(vis_model_pre_flipped)

vis_model_post_flipped <- glmer(SamplesInAOI / SamplesTotal ~ group * TimeBin * trial_num_scaled + (1 | id), data = vis_model_data_post_flipped, family = binomial, weights = SamplesTotal, control=glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000))) 

summary(vis_model_post_flipped)


###----------------------------------------------------MODEL RESULTS TABLES
# 
tab_model(aud_model_pre_flipped, show.re.var = FALSE, show.icc = FALSE)
tab_model(aud_model_post_flipped, show.re.var = FALSE, show.icc = FALSE)
tab_model(vis_model_pre_flipped, show.re.var = FALSE, show.icc = FALSE)
tab_model(vis_model_post_flipped, show.re.var = FALSE, show.icc = FALSE)


```

##Plot actual model data stacked

```{r}

##-----------------------------------------------------------AUDITORY


aud_model_data_pre %>% 
  #filter(trial_num < 10) %>% #uncomment to see data with only trials 1-9
  ggplot(aes(x = TimeBin, y = Prop, color = as.factor(trial_num_scaled))) + 
  geom_jitter(alpha = 0.8, shape = 21, stroke = .75) + 
  geom_smooth(aes(color = as.factor(trial_num_scaled)), se = FALSE) + 
  facet_grid( ~ group) + 
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  labs(color = "trial_num", title = "Pre-Switch (Auditory)")
#ggsave("plot_model_data_7pre.png", path = here("figures"), device = "png", width = 7, height = 4, units = "in",
#   dpi = 300)



aud_model_data_post %>% 
  #filter(trial_num < 10) %>%
  ggplot(aes(x = TimeBin, y = Prop, color = as.factor(trial_num_scaled))) + 
  geom_jitter(alpha = 0.8, shape = 21, stroke = .75) + 
  geom_smooth(aes(color = as.factor(trial_num_scaled)), se = FALSE) + 
  facet_grid( ~ group) +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  labs(color = "trial_num", title = "Post-Switch (Auditory)")
#ggsave("plot_model_data_7post.png", path = here("figures"), device = "png", width = 7, height = 4, units = "in",
#   dpi = 300)


##-----------------------------------------------------------VISUAL


vis_model_data_pre %>% 
  #filter(trial_num < 10) %>%
  ggplot(aes(x = TimeBin, y = Prop, color = as.factor(trial_num_scaled))) + 
  geom_jitter(alpha = 0.8, shape = 21, stroke = .75) + 
  geom_smooth(aes(color = as.factor(trial_num_scaled)), se = FALSE) + 
  facet_grid( ~ group) + 
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  labs(color = "trial_num", title = "Pre-Switch (Visual)")
#ggsave("plot_model_data_7pre.png", path = here("figures"), device = "png", width = 7, height = 4, units = "in",
#   dpi = 300)



vis_model_data_post %>% 
  #filter(trial_num < 10) %>%  
  ggplot(aes(x = TimeBin, y = Prop, color = as.factor(trial_num_scaled))) + 
  geom_jitter(alpha = 0.8, shape = 21, stroke = .75) + 
  geom_smooth(aes(color = as.factor(trial_num_scaled)), se = FALSE) + 
  facet_grid( ~ group) +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  labs(color = "trial_num", title = "Post-Switch (Visual)")
#ggsave("plot_model_data_7post.png", path = here("figures"), device = "png", width = 7, height = 4, units = "in",
#   dpi = 300)

  
```




##Plot model predicted values

```{r}

##-----------------------------------AUDITORY

ggpredict(aud_model_pre, terms = c("TimeBin", "trial_num_scaled [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]", "group"), type = "fe", ci.lvl = FALSE) %>% plot(colors = "trial_num_scaled", line.size = 1, connect.lines = TRUE) +
  labs(title = "Predicted values of proportion looking to target during the Training phase \nin Experiment 1c (Auditory condition)", x = "Time in milliseconds during anticipation period", y = "Proportion looking to target", color = "Trial number") +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  scale_x_continuous(breaks = c(0, 2, 4), labels = c("0", "500", "1000")) +
  ylim(-0.1, 1) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))

ggpredict(aud_model_post, terms = c("TimeBin", "trial_num_scaled [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]", "group"), type = "fe", ci.lvl = FALSE) %>% plot(colors = "trial_num_scaled", line.size = 1, connect.lines = TRUE) +
  labs(title = "Predicted values of proportion looking to target during the Test phase \nin Experiment 1c (Auditory condition)", x = "Time in milliseconds during anticipation period", y = "Proportion looking to target", color = "Trial number") +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  scale_x_continuous(breaks = c(0, 2, 4), labels = c("0", "500", "1000")) +
  ylim(-0.1, 1) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))


##-----------------------------------VISUAL

ggpredict(vis_model_pre, terms = c("TimeBin", "trial_num_scaled [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]", "group"), type = "fe", ci.lvl = FALSE) %>% plot(colors = "trial_num_scaled", line.size = 1, connect.lines = TRUE) +
  labs(title = "Predicted values of proportion looking to target during the Training phase \nin Experiment 1c (Visual condition)", x = "Time in milliseconds during anticipation period", y = "Proportion looking to target", color = "Trial number") +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  scale_x_continuous(breaks = c(0, 2, 4), labels = c("0", "500", "1000")) +
  ylim(-0.1, 1) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))

ggpredict(vis_model_post, terms = c("TimeBin", "trial_num_scaled [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]", "group"), type = "fe", ci.lvl = FALSE) %>% plot(colors = "trial_num_scaled", line.size = 1, connect.lines = TRUE) +
  labs(title = "Predicted values of proportion looking to target during the Test phase \nin Experiment 1c (Visual condition)", x = "Time in milliseconds during anticipation period", y = "Proportion looking to target", color = "Trial number") +
  scale_color_manual(values = blues, labels = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)) +
  scale_x_continuous(breaks = c(0, 2, 4), labels = c("0", "500", "1000")) +
  ylim(-0.1, 1) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0)))
```
#Analysis with their full sample

##Problems with their data...

```{r}


#-----------------------------The following numbers for Auditory condition are very close to Kalashnikova's

aud_all %>%
  mutate(auditory_tl = case_when(id == "5314" ~ visual_tl, 
                                 TRUE ~ auditory_tl)) %>%
  filter(auditory_tl <= .6) %>%
  filter(bin_start_time >= 2250 & bin_start_time <= 3250) %>%
  mutate(trial_type = case_when(trial_index > 12 ~ "post_switch",
                                TRUE ~ "pre-switch")) %>%
  filter(loss != 1) %>%
  filter(left + right > 0) %>%
  group_by(id, group, trial_type, trial_index) %>%
  summarize(prop_target = mean(target == TRUE, na.rm = TRUE))  %>%
  mutate(block = case_when(trial_index > 20 ~ 3,
                           trial_index > 16 ~ 2,
                           trial_index > 12 ~ 1,
                           trial_index > 8 ~ 3,
                           trial_index > 4 ~ 2,
                           trial_index > 0 ~ 1,
                           TRUE ~ NA_real_)) %>% 
  group_by(id, block, group, trial_type) %>%
  summarize(prop_target = mean(prop_target),
            n = length(unique(id))) %>%
  #get means
  
  group_by(block, group, trial_type) %>%
  summarize(mean = round(mean(prop_target, na.rm = TRUE), digits = 2),
            sd = round(sd(prop_target, na.rm = TRUE), digits = 2),
            n = sum(n)) %>%
  pivot_wider(id_cols = c(trial_type, block), names_from = group, values_from = c(mean, sd, n)) %>%
  select(trial_type, block, mean_monolingual, sd_monolingual, n_monolingual, mean_bilingual, sd_bilingual, n_bilingual) %>%
  arrange(desc(trial_type), block) %>% View()


#-----------------------------The following numbers for Visual condition are very close to Kalashnikova's, proving that they analyzed the incorrect time window. What they analyzed was NOT the anticipation period, but instead when the kids were all looking at the circle

vis_all %>%
  mutate(visual_tl = case_when(id == "5314" ~ auditory_tl, 
                                 TRUE ~ visual_tl)) %>%
  filter(visual_tl <= .6) %>%
  filter(original_start_time >= 2250 & original_start_time <= 3250) %>%
  mutate(trial_type = case_when(trial_index > 12 ~ "post_switch",
                                TRUE ~ "pre-switch")) %>%
  filter(loss != 1) %>%
  filter(left + right > 0) %>%
  group_by(id, group, trial_type, trial_index) %>%
  summarize(prop_target = mean(target == TRUE, na.rm = TRUE))  %>%
  mutate(block = case_when(trial_index > 20 ~ 3,
                           trial_index > 16 ~ 2,
                           trial_index > 12 ~ 1,
                           trial_index > 8 ~ 3,
                           trial_index > 4 ~ 2,
                           trial_index > 0 ~ 1,
                           TRUE ~ NA_real_)) %>% 
  group_by(id, block, group, trial_type) %>%
  summarize(prop_target = mean(prop_target),
            n = length(unique(id))) %>%
  #get means
  
  group_by(block, group, trial_type) %>%
  summarize(mean = round(mean(prop_target, na.rm = TRUE), digits = 2),
            sd = round(sd(prop_target, na.rm = TRUE), digits = 2),
            n = sum(n)) %>%
  pivot_wider(id_cols = c(trial_type, block), names_from = group, values_from = c(mean, sd, n)) %>%
  select(trial_type, block, mean_monolingual, sd_monolingual, n_monolingual, mean_bilingual, sd_bilingual, n_bilingual) %>%
  arrange(desc(trial_type), block) %>% View()


  
##----------------------try visual condition again with more appropriate anticipation period and the attention-getter times removed
  
  
vis_all %>%
  mutate(visual_tl = case_when(id == "5314" ~ auditory_tl, 
                                 TRUE ~ visual_tl)) %>%
  filter(visual_tl <= .6) %>%
  filter(bin_start_time >= 3650 & bin_start_time <= 4650) %>%
  mutate(trial_type = case_when(trial_index > 12 ~ "post_switch",
                                TRUE ~ "pre-switch")) %>%
  filter(loss != 1) %>%
  filter(left + right > 0) %>%
  group_by(id, group, trial_type, trial_index) %>%
  summarize(prop_target = mean(target == TRUE, na.rm = TRUE))  %>%
  mutate(block = case_when(trial_index > 20 ~ 3,
                           trial_index > 16 ~ 2,
                           trial_index > 12 ~ 1,
                           trial_index > 8 ~ 3,
                           trial_index > 4 ~ 2,
                           trial_index > 0 ~ 1,
                           TRUE ~ NA_real_)) %>% 
  group_by(id, block, group, trial_type) %>%
  summarize(prop_target = mean(prop_target),
            n = length(unique(id))) %>%
  #get means
  
  group_by(block, group, trial_type) %>%
  summarize(mean = round(mean(prop_target, na.rm = TRUE), digits = 2),
            sd = round(sd(prop_target, na.rm = TRUE), digits = 2),
            n = sum(n)) %>%
  pivot_wider(id_cols = c(trial_type, block), names_from = group, values_from = c(mean, sd, n)) %>%
  select(trial_type, block, mean_monolingual, sd_monolingual, n_monolingual, mean_bilingual, sd_bilingual, n_bilingual) %>%
  arrange(desc(trial_type), block) %>% View()
  
  
#-------------------------------------------How many N per trial?

aud_all %>%
  mutate(auditory_tl = case_when(id == "5314" ~ visual_tl, 
                                 TRUE ~ auditory_tl)) %>%
  filter(auditory_tl <= .6) %>%
  filter(bin_start_time >= 2250 & bin_start_time <= 3250) %>%
  mutate(trial_type = case_when(trial_index > 12 ~ "post_switch",
                                TRUE ~ "pre-switch")) %>%
  filter(loss != 1) %>%
  filter(left + right > 0) %>%
  group_by(group, trial_type, trial_index) %>%
  summarize(n = length(unique(id))) %>% 
  ungroup() %>%
  arrange(group, desc(trial_type), trial_index) %>% View()

vis_all %>%
  mutate(auditory_tl = case_when(id == "5314" ~ auditory_tl, 
                                 TRUE ~ visual_tl)) %>%
  filter(visual_tl <= .6) %>%
  filter(original_start_time >= 2250 & original_start_time <= 3250) %>%
  mutate(trial_type = case_when(trial_index > 12 ~ "post_switch",
                                TRUE ~ "pre-switch")) %>%
  filter(loss != 1) %>%
  filter(left + right > 0) %>%
  group_by(group, trial_type, trial_index) %>%
  summarize(n = length(unique(id))) %>% 
  ungroup() %>%
  arrange(group, desc(trial_type), trial_index) %>% View()

vis_all %>%
  mutate(auditory_tl = case_when(id == "5314" ~ auditory_tl, 
                                 TRUE ~ visual_tl)) %>%
  filter(visual_tl <= .6) %>%
  filter(bin_start_time >= 3650 & bin_start_time <= 4650) %>%
  mutate(trial_type = case_when(trial_index > 12 ~ "post_switch",
                                TRUE ~ "pre-switch")) %>%
  filter(loss != 1) %>%
  filter(left + right > 0) %>%
  group_by(group, trial_type, trial_index) %>%
  summarize(n = length(unique(id))) %>% 
  ungroup() %>%
  arrange(group, desc(trial_type), trial_index) %>% View()

#---------------------------Block means by baby 

aud_by_part_means_original <- aud_all %>%
  mutate(auditory_tl = case_when(id == "5314" ~ visual_tl, 
                                 TRUE ~ auditory_tl)) %>%
  filter(auditory_tl <= .6) %>%
  filter(bin_start_time >= 2250 & bin_start_time <= 3250) %>%
  mutate(trial_type = case_when(trial_index > 12 ~ "post_switch",
                                TRUE ~ "pre-switch")) %>%
  filter(loss != 1) %>%
  filter(left + right > 0) %>%
  group_by(id, group, trial_type, trial_index) %>%
  summarize(prop_target = mean(target == TRUE, na.rm = TRUE),
            prop_distractor = mean(distractor == TRUE, na.rm = TRUE))  %>%
  mutate(binary_score = case_when(prop_target > prop_distractor ~ 1, 
                                  TRUE ~ 0)) %>%
  mutate(block = case_when(trial_index > 20 ~ 3,
                           trial_index > 16 ~ 2,
                           trial_index > 12 ~ 1,
                           trial_index > 8 ~ 3,
                           trial_index > 4 ~ 2,
                           trial_index > 0 ~ 1,
                           TRUE ~ NA_real_)) %>% 
  group_by(id, block, group, trial_type) %>%
  summarize(prop_target = mean(prop_target),
            prop_score = mean(binary_score),
            n = length(unique(id))) %>%
  arrange(block, desc(trial_type), id)



vis_by_part_means_original <- vis_all %>%
  mutate(visual_tl = case_when(id == "5314" ~ auditory_tl, 
                                 TRUE ~ visual_tl)) %>%
  filter(visual_tl <= .6) %>%
  filter(original_start_time >= 2250 & original_start_time <= 3250) %>%
  mutate(trial_type = case_when(trial_index > 12 ~ "post_switch",
                                TRUE ~ "pre-switch")) %>%
  filter(loss != 1) %>%
  filter(left + right > 0) %>%
  group_by(id, group, trial_type, trial_index) %>%
  summarize(prop_target = mean(target == TRUE, na.rm = TRUE),
            prop_distractor = mean(distractor == TRUE, na.rm = TRUE))  %>%
  mutate(binary_score = case_when(prop_target > prop_distractor ~ 1, 
                                  TRUE ~ 0)) %>%
  mutate(block = case_when(trial_index > 20 ~ 3,
                           trial_index > 16 ~ 2,
                           trial_index > 12 ~ 1,
                           trial_index > 8 ~ 3,
                           trial_index > 4 ~ 2,
                           trial_index > 0 ~ 1,
                           TRUE ~ NA_real_)) %>% 
  group_by(id, block, group, trial_type) %>%
  summarize(prop_target = mean(prop_target),
            prop_score = mean(binary_score),
            n = length(unique(id))) %>%
  arrange(block, desc(trial_type), id)


vis_by_part_means_adjusted <- vis_all %>%
  mutate(visual_tl = case_when(id == "5314" ~ auditory_tl, 
                                 TRUE ~ visual_tl)) %>%
  filter(visual_tl <= .6) %>%
  filter(bin_start_time >= 3650 & bin_start_time <= 4650) %>%
  mutate(trial_type = case_when(trial_index > 12 ~ "post_switch",
                                TRUE ~ "pre-switch")) %>%
  filter(loss != 1) %>%
  filter(left + right > 0) %>%
  group_by(id, group, trial_type, trial_index) %>%
  summarize(prop_target = mean(target == TRUE, na.rm = TRUE),
            prop_distractor = mean(distractor == TRUE, na.rm = TRUE))  %>%
  mutate(binary_score = case_when(prop_target > prop_distractor ~ 1, 
                                  TRUE ~ 0)) %>%
  mutate(block = case_when(trial_index > 20 ~ 3,
                           trial_index > 16 ~ 2,
                           trial_index > 12 ~ 1,
                           trial_index > 8 ~ 3,
                           trial_index > 4 ~ 2,
                           trial_index > 0 ~ 1,
                           TRUE ~ NA_real_)) %>% 
  group_by(id, block, group, trial_type) %>%
  summarize(prop_target = mean(prop_target),
            prop_score = mean(binary_score),
            n = length(unique(id))) %>%
  arrange(block, desc(trial_type), id)

  
m1 <- lmer(prop_target ~ group * trial_type + block + (1 | id), data = aud_by_part_means_original) #very similar results to Kalashnikova, despite singular fit
m2 <- lmer(prop_target ~ group * trial_type + block + (1 | id), data = vis_by_part_means_original) #very similar results to Kalashnikova
m3 <- lmer(prop_target ~ group * trial_type + block + (1 | id), data = vis_by_part_means_adjusted) #singular fit



#---------------------------check if typo matches trackloss for another ID

vis_left %>% filter(str_detect(id, "5332")) %>% make_eyetrackingr_data(participant_column = "id",
                                                                       trackloss_column = "loss",
                                                                       time_column = "bin_start_time",
                                                                       trial_column = "trial_index",
                                                                       aoi_columns = c("left", "right", "center"),
                                                                       treat_non_aoi_looks_as_missing = TRUE) %>%
  trackloss_analysis()


```

##OLD MESSY CODE NOT NEEDED

```{r}
# aud_all %>%
# 
#   group_by(bin_start_time, trial_num, trial_type, group) %>%
#   mutate(target_prop = mean(target == "TRUE"),
#          distractor_prop = mean(distractor == "TRUE"),
#          centre_prop = mean(center == "TRUE"),
#          total_prop = (left_prop + right_prop + centre_prop)) %>%
#   pivot_longer(left_prop:total_prop, names_to = "side", values_to = "prop") %>%
#   ggplot(aes(x = bin_start_time, y = prop, color = side)) +
#   geom_line() +
#   scale_y_continuous(limits = c(0, 1)) +
#   facet_grid(trial_num ~ trial_type)
#   
# vis_all %>%
#   
#   filter(!is.na(group)) %>%
#   group_by(bin_start_time, trial_num, trial_type, group) %>%
#   mutate(target_prop = mean(target == "TRUE"),
#          distractor_prop = mean(distractor == "TRUE"),
#          centre_prop = mean(center == "TRUE")) %>%
#   pivot_longer(target_prop:centre_prop, names_to = "side", values_to = "prop") %>%
#   ggplot(aes(x = bin_start_time, y = prop, color = group, linetype = side)) +
#   geom_line() +
#   scale_y_continuous(limits = c(0, 1)) +
#   facet_grid(trial_num ~ trial_type)
# 
# ggsave("plot.png")
# 
#   
#   
# 
# final_sample_vis_full_trial %>%
#   filter(Time >= 1550 & Time <= 4150 & !is.na(group) & trial_num == 1) %>%
#   ggplot(aes(x = Time, y = Prop, linetype = AOI, color = group)) +
#   geom_smooth(se= FALSE) +
#   facet_wrap( ~ trial_type)
# 
# final_sample_aud_full_trial %>%
#   filter(Time >= 1550 & Time <= 4150 & !is.na(group) & trial_num == 1) %>%
#   ggplot(aes(x = Time, y = Prop, linetype = AOI, color = group)) +
#   geom_smooth(se= FALSE) +
#   facet_wrap( ~ trial_type)
# 
#   
# aud_model_data %>%
#   ggplot(aes(x = TimeBin, y = Prop, color = group)) +
#   geom_smooth(se = FALSE) +
#   facet_grid(trial_type ~ trial_num)
# 
# vis_all %>% mutate(message2 = case_when(is.na(parse_number(message)) ~ message, TRUE ~ NA_character_)) %>% select(message2, bin_start_time) %>% filter(!is.na(message2)) %>% distinct()

### Anticipation period is obviously wrong
# 
# vis_left %>% 
#   filter(bin_start_time > 0) %>%
#   mutate(target = case_when(trial_index <= 12 ~ left,
#                             trial_index >= 13 ~ right),
#          ant_start = case_when(message == "Ant Start" ~ bin_start_time,
#                                TRUE ~ NA_real_),
#          rew_start = case_when(message == "Reward" ~ bin_start_time,
#                                TRUE ~ NA_real_)) %>% 
#   group_by(bin_start_time, trial_index, ant_start, rew_start) %>%
#   summarize(prop = mean(target == TRUE)) %>%
#   ggplot(aes(x = bin_start_time, y = prop)) + 
#   geom_point() + 
#   facet_wrap(~ trial_index) + 
#   annotate("rect", xmin = 2250, xmax = 3250, ymin = 0, ymax = 1,
#   alpha = .2)




# novel <- read_csv(here("for_amg.csv"))
# novel_ids <- read_csv(here("amg_ids.csv"))
# 
# novel %>% inner_join(novel_ids, by = c("baby_id", "study_name")) %>%
#   mutate(en_data = case_when(!is.na(en_1) | !is.na(en_2) | !is.na(en_3) ~ "yes",
#                              TRUE ~ "no"),
#          fr_data = case_when(!is.na(fr_1) | !is.na(fr_2) | !is.na(fr_3) ~ "yes",
#                              TRUE ~ "no"),
#          en_comp = case_when(is.na(en_comp) & en_data == "yes" ~ 0,
#                              en_data == "no" ~ NA_real_,
#                              TRUE ~ en_comp),
#          en_prod = case_when(is.na(en_prod) & en_data == "yes" ~ 0,
#                              en_data == "no" ~ NA_real_,
#                              TRUE ~ en_prod),
#          fr_comp = case_when(is.na(fr_comp) & fr_data == "yes" ~ 0,
#                              fr_data == "no" ~ NA_real_,
#                              TRUE ~ fr_comp),
#          fr_prod = case_when(is.na(fr_prod) & fr_data == "yes" ~ 0,
#                              fr_data == "no" ~ NA_real_,
#                              TRUE ~ fr_prod)) %>%
#   select(baby_id, study_name, en_data, en_comp, en_prod, fr_data, fr_comp, fr_prod) %>%
#   write_csv("cdi_missing_info.csv")

```


