---
title: "raw_data_analysis"
author: "Hilary Killam"
date: "January 27, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

## Load packages
library(tidyverse)
library(readxl)
library(stringr)
library(tidyr)
library(ggplot2)
library(car)
library(ez)
library(snakecase)
library(janitor)
library(lme4)
library(effects)
library(emmeans)
library(apaTables)
library(here)
library(eyetrackingR)
options(scipen = 999)

kovacs09 <- "Kovács & Mehler 2009"

## Define minimum looking and minimum trial numbers for this study
MIN_LOOK_PROPORTION <- .5
MIN_NUMBER_TRIALS <- 5

```


```{r load_clean_merge_data, include = FALSE}

###----------------------------------------------------------------------LOAD DATA----------------------------------------------------------------------------

load(here("data", "tobii_full_export.Rda")) #full export data is saved as RDA file since the csv is too large for GitHub

## Read in MSL data
ms_list <- read_csv(here("data", "2019_CogControl_MSL.csv"), na = "-") %>%
  separate(lang.group,into = c("language", "group")) %>%
  filter(keeper == 1) 
colnames(ms_list) <- to_snake_case(colnames(ms_list)) #make everything snake case so it's easier to remember variable names

###----------------------------------------------------------------------PREP MSL DATA----------------------------------------------------------------------------

ms_list <- ms_list %>%  
  mutate(age_group = fct_rev(as.factor(age_group))) %>%
  mutate(language = fct_rev(as.factor(language))) %>%
  mutate(total_vocab_prod = as.numeric(total_vocab_prod)) %>%
  mutate(total_concept_prod = as.numeric(total_concept_prod)) %>%
  mutate(recording_name = as_factor(recording_name)) %>%
  mutate(gender = as.factor(gender)) %>%
  group_by(language) %>%
  mutate(median_by_group = median(total_vocab_prod,na.rm = T)) %>%
  mutate(vocab_group = ifelse(median_by_group > total_vocab_prod,
                              "Low", 
                              "High")) %>%
  mutate(vocab_group = as.factor(vocab_group)) 


###----------------------------------------------------------------------PREP TOBII DATA-------------------------------------------------------------- 

data_tobii_cleaned <- tobii_full_export %>%
   #head(n = 2500) %>% # uncomment this line to test code changes on a subset of the full dataset since running the whole thing takes awhile
  select(StudioTestName, RecordingName, RecordingDuration, MediaName, RecordingTimestamp, StudioEvent, FixationIndex, GazeEventType, GazeEventDuration, `GazePointX (ADCSpx)`, `GazePointY (ADCSpx)`, ValidityLeft, ValidityRight) %>% # choose only needed columns
  mutate(RecordingName = case_when(RecordingName == "Cogcontrol20_S116_48375" ~ "CogControl20_S116_48375",
                                    RecordingName != "Cogcontrol20_S116_48375" ~ RecordingName)) %>% #fix typo from Tobii
  rename(gaze_point_X = `GazePointX (ADCSpx)`, gaze_point_y = `GazePointY (ADCSpx)`, timestamp = `RecordingTimestamp`, order = StudioTestName) %>% #fix names (newname = oldname)
  mutate(MediaName = gsub(".wmv", "", MediaName)) %>% # drops the .wmv part.
  mutate(trial_num = parse_number(MediaName)) %>% #get trial number
  mutate(trial_type = as.factor(case_when(str_detect(MediaName, "Training") ~ "pre-switch", #get trial type
                                 str_detect(MediaName, "Test") ~ "post-switch"))) %>% #get trial type
  mutate(trial_name = as.factor(str_c(trial_type, trial_num, sep = "_"))) %>% #combine trial number and trial type into a trial name (for example, "post-switch_3"")
  mutate(trial_unique = as.factor(str_c(RecordingName, trial_name, sep = "_"))) %>% #get a trial identifier that is unique to each participant, trial number, and trial type
  filter(RecordingName != "test") %>% #gets rid of a "test" recording that somehow got exported
  mutate(MediaName = as.factor(MediaName)) %>%
  group_by(trial_unique) %>%
  mutate(trial_start = min(timestamp)) %>%
  mutate(trial_end = max(timestamp)) %>%
  mutate(trial_from_zero = timestamp - trial_start) %>% #make time stamps start from 0 for each trial
  ungroup() %>%
  filter(!is.na(ValidityLeft) & !is.na(ValidityRight)) %>% #gets rid of Movie Start and Movie End rows that duplicate some info and don't have meaningful validity data or gaze point info
  mutate(trackloss = case_when(is.na(gaze_point_X) ~ TRUE, #creates a trackloss column that will be used in the eyetrackingR functions
                                is.na(gaze_point_y) ~ TRUE,
                                ValidityLeft > 1 & ValidityRight > 1 ~ TRUE,
                                TRUE ~ FALSE)) %>%
  clean_names() %>% #makes everything snake case 
  ###-------------------------------------------------------------------make target aoi coordinates:
   mutate(aoi_target_x_left = case_when(order == "Order 1" & trial_type == "pre-switch" ~ 10,
                                        order == "Order 1" & trial_type == "post-switch" ~ 1260,
                                        order == "Order 2" & trial_type == "pre-switch" ~ 1260,
                                        order == "Order 2" & trial_type == "post-switch" ~ 10)) %>%
  mutate(aoi_target_x_length = case_when(!is.na(trial_type) ~ 645)) %>%
  mutate(aoi_target_x_right = aoi_target_x_left + aoi_target_x_length) %>%
  mutate(aoi_target_y_top = case_when(!is.na(trial_type) ~ 270)) %>%
  mutate(aoi_target_y_length = case_when(!is.na(trial_type) ~ 650)) %>%
  mutate(aoi_target_y_bottom = aoi_target_y_top + aoi_target_y_length) %>%
  ###-------------------------------------------------------------------make distractor aoi coordinates:
  mutate(aoi_distractor_x_left = case_when(order == "Order 1" & trial_type == "pre-switch" ~ 1260,
                                        order == "Order 1" & trial_type == "post-switch" ~ 10,
                                        order == "Order 2" & trial_type == "pre-switch" ~ 10,
                                        order == "Order 2" & trial_type == "post-switch" ~ 1260)) %>%
  mutate(aoi_distractor_x_length = case_when(!is.na(trial_type) ~ 645)) %>%
  mutate(aoi_distractor_x_right = aoi_distractor_x_left + aoi_distractor_x_length) %>%
  mutate(aoi_distractor_y_top = case_when(!is.na(trial_type) ~ 270)) %>%
  mutate(aoi_distractor_y_length = case_when(!is.na(trial_type) ~ 650)) %>%
  mutate(aoi_distractor_y_bottom = aoi_distractor_y_top + aoi_distractor_y_length) %>%
  ###-------------------------------------------------------------------make circle aoi coordinates:
  mutate(aoi_circle_x_left = case_when(!is.na(trial_type) ~ 758)) %>%
  mutate(aoi_circle_x_length = case_when(!is.na(trial_type) ~ 385)) %>%
  mutate(aoi_circle_x_right = case_when(!is.na(trial_type) ~ aoi_circle_x_left + aoi_circle_x_length)) %>%  
  mutate(aoi_circle_y_top = case_when(!is.na(trial_type) ~ 400)) %>%
  mutate(aoi_circle_y_length = case_when(!is.na(trial_type) ~ 385)) %>%
  mutate(aoi_circle_y_bottom = case_when(!is.na(trial_type) ~ aoi_circle_x_left + aoi_circle_x_length)) %>%  
  filter(!is.na(media_name)) %>% #remove lines with no media name
  filter(!is.na(trial_unique)) %>% #remove NA unique trials (gets rid of times outside our trial windows that aren't interesting to us)
  filter(is.na(studio_event)) %>% #get rid of MovieStart and MovieEnd lines since they have duplicate timestamps
  mutate(remove_row = case_when(timestamp == 66398 & trial_unique == "CogControl20_S01_42270_Test_Target_Right_4.wmv" & is.na(validity_left) ~ "remove",
                                timestamp == 85782 & trial_unique == "CogControl20_S01_42270_Test_Target_Right_7.wmv" & is.na(validity_left) ~ "remove",
                                timestamp == 35816 & trial_unique == "CogControl7_S24_44771_Training_Target_Left_7.wmv" & is.na(validity_left) ~ "remove",
                                TRUE ~ "keep"))%>% #this identifies 3 rows with duplicate timestamps, but inexplicably without the fixation gaze data, that prevent the eyetrackingR code from running correctly
  filter(remove_row == "keep") %>% #get rid of those 3 weird rows from above

  ###-------------------------------------------------------------------get AOI look per time point:
  mutate(target = case_when(gaze_point_x > aoi_target_x_left & gaze_point_x < aoi_target_x_right & gaze_point_y > aoi_target_y_top & gaze_point_y < aoi_target_y_bottom ~ 1,
                                 TRUE ~ 0)) %>% #looks to target
  mutate(distractor = case_when(gaze_point_x > aoi_distractor_x_left & gaze_point_x < aoi_distractor_x_right & gaze_point_y > aoi_distractor_y_top & gaze_point_y < aoi_distractor_y_bottom ~ 1,
                                 TRUE ~ 0)) %>% #looks to distractor
  mutate(circle = case_when(gaze_point_x > aoi_circle_x_left & gaze_point_x < aoi_circle_x_right & gaze_point_y > aoi_circle_y_top & gaze_point_y < aoi_circle_y_bottom ~ 1,
                                 TRUE ~ 0)) %>% #looks to circle
  mutate(look_any = case_when(target == 1 | distractor == 1 | circle == 1 ~ 1,
                              TRUE ~ 0)) #looks to either target, distractor, or circle
          

#save(data_tobii_cleaned, file = here("data", "data_tobii_cleaned.Rda"))


###----------------------------------------------------------------------CREATE MERGED FULL DATA----------------------------------------------------------------------------  

data_merged <- inner_join(data_tobii_cleaned, ms_list, by = "recording_name") %>%
  mutate(recording_name = as.factor(recording_name))


###----------------------------------------------------------------------GET ANTICIPATION PERIOD KEEPERS--------------------------------------------------------

data_anticipation <- data_merged %>%
  filter(trial_from_zero >= 2150 & trial_from_zero <= 3150) %>% #filter to just the aniticpatory period, which is 150 ms after the offset of the 1000 ms cue, and lasts for 1000 ms
  group_by(trial_unique) %>%
  mutate(prop_fixations = mean(look_any)) %>%
  filter(prop_fixations >= MIN_LOOK_PROPORTION) %>% #removes trials where the child did not fixate on anything for at least 50% of the anticipation period
  group_by(recording_name, trial_type) %>% 
  mutate(num_good_trials = length(unique(trial_num))) %>%
  filter(num_good_trials >= MIN_NUMBER_TRIALS) %>% #removes babies who don't have the minimum number of trials 
  group_by(recording_name) %>%
  mutate(num_trial_types = length(unique(trial_type))) %>%
  filter(num_trial_types == 2) %>% #removes babies who don't have data in both trial types
  ungroup()

final_sample_ids <- data_anticipation %>% #used for creating data_full_trials object for plotting whole trial
  select(recording_name) %>%
  unique()

data_full_trials <- data_merged %>%
  inner_join(final_sample_ids, by = "recording_name") # this is the full time series data, but only for infants that made it through to the final anticipation-period sample. Will be used for ploting time series data of whole trial

###----------------------------------------------------------------------FINAL SAMPLE COUNTS PER GROUP---------------------------------------------------------  

data_full_trials %>%
  group_by(language, age_group) %>%
  summarize(length(unique(recording_name)))

```

```{r eyetrackingR, echo = FALSE}

###----------------------------------------------------------------------CREATE EYETRACKINGR DATA FOR FULL TRIALS----------------------------------------------

data_eyetracking_full_trials <- make_eyetrackingr_data(data_full_trials, 
                                participant_column = "recording_name",
                                trial_column = "trial_name", 
                                time_column = "trial_from_zero",
                                trackloss_column = "trackloss",
                                aoi_columns = c('target', 'circle', 'distractor'),
                                treat_non_aoi_looks_as_missing = TRUE)

full_trial <- subset_by_window(data_eyetracking_full_trials,
                                     window_start_time = 0,
                                     window_end_time = 5000, rezero = TRUE, remove = TRUE)

data_time_series_full <- make_time_sequence_data(data_eyetracking_full_trials,
                                         time_bin_size = 100,
                                         predictor_columns = c("language", "age_group", "total_vocab_prod", "trial_type", "trial_num"),
                                         aois = c("target", "distractor"))

###----------------------------------------------------------------------CREATE EYETRACKINGR DATA FOR ANTICIPATION PERIOD------------------------------------

data_eyetracking_antic <- subset_by_window(data_eyetracking_full_trials,
                                     window_start_time = 2150,
                                     window_end_time = 3150, rezero = TRUE, remove = TRUE)

trackloss <- trackloss_analysis(data = data_eyetracking_antic)

data_eyetracking_clean <- clean_by_trackloss(data = data_eyetracking_antic, trial_prop_thresh = .5) 

data_time_series_antic <- make_time_sequence_data(data_eyetracking_clean,
                                         time_bin_size = 100,
                                         predictor_columns = c("language", "age_group", "total_vocab_prod", "trial_type", "trial_num"),
                                         aois = c("target"))

```

``` {r time_series_plots, echo = FALSE}

#-----------------------------------------------------------EyetrackingR Plots - not as flexible as ggplot so will try below with ggplot
# plot7_full_trial <- data_time_series %>%
#   filter(age_group == "7 months") %>%
#   plot(predictor_column = "trial_type")
# 
# plot7_full_trial
# 
# plot20_full_trial <- data_time_series %>%
#   filter(age_group == "20 months") %>%
#   plot(predictor_column = "trial_type")
# 
# plot20_full_trial

###----------------------------------------------------------------------PLOT FULL TRIALS-------------------------------------------------------------  

time_series_full_trial <- data_time_series_full %>%
  pivot_wider(names_from = AOI, values_from = Prop) %>%
  mutate(trial_type = fct_rev(trial_type)) %>%
  group_by(trial_type, language, age_group, Time, trial_num) %>%
  summarise(target = mean(target, na.rm=TRUE),
            distractor = mean(distractor, na.rm=TRUE))  %>%
  pivot_longer(cols = c(target, distractor), names_to = "aoi", values_to = "prop_looking") %>%
  mutate(aoi = factor(aoi, levels = c("target", "distractor")))  %>%
  mutate(trial_labels = paste0("Trial ", trial_num)) %>%
  group_by(age_group) %>%
  nest() %>%
  #create nested data for easily plotting more than one of the same plot by a group
  mutate(plot = map2(data, age_group, ~ ggplot(data = .x, aes(x = Time, y = prop_looking, color = aoi, linetype = language)) + 
  geom_line() +
  facet_grid(trial_labels ~ trial_type) +
  annotate("rect", xmin = 2150, xmax = 3150, ymin = -Inf, ymax = Inf, fill = "red", alpha = 0.07) +
  annotate("text", x = 2650, y = 0.9, label = "Anticipation \n Period", size = 2.5, color = "#927774") +
  ggtitle(age_group) +
  theme(plot.title = element_text(hjust = 0.5)) +
  xlab("Time from trial start (ms)")  +
  ylab("Proportion looking")))
  
time_series_full_trial$plot[[1]]
time_series_full_trial$plot[[2]]

# ggsave("full_trials_7_200.png", path = here("figures"), plot = time_series_summary$plot[[1]], device = "png", width = 15, height = 10, units = "in",
#   dpi = 300)
# 
# ggsave("full_trials_20_200.png", path = here("figures"), plot = time_series_summary$plot[[2]], device = "png", width = 15, height = 10, units = "in",
#   dpi = 300)


###----------------------------------------------------------------------PLOT ANTICIPATION PERIOD-------------------------------------------------------------  

time_series_antic <- data_time_series_antic %>%
  pivot_wider(names_from = AOI, values_from = Prop) %>%
  mutate(trial_type = fct_rev(trial_type)) %>%
  group_by(trial_type, language, age_group, trial_num) %>%
  summarise(target = mean(target, na.rm=TRUE),
            distractor = mean(distractor, na.rm=TRUE))  %>%
  pivot_longer(cols = c(target, distractor), names_to = "aoi", values_to = "prop_looking") %>%
  mutate(aoi = factor(aoi, levels = c("target", "distractor")))  %>%
  mutate(trial_labels = paste0("Trial ", trial_num)) %>%
  group_by(age_group) %>%
  nest() %>%
  mutate(plot = map2(data, age_group, ~ ggplot(data = .x, aes(x = (trial_num), y = prop_looking, color = aoi, linetype = language)) + 
  geom_smooth(se = FALSE) +
  facet_grid( ~ trial_type) +
  ggtitle(age_group) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9)) +  
  xlab("Trial Number")  +
  ylab("Proportion looking")))
  
antic_7_plot <- time_series_antic$plot[[1]]
antic_20_plot <- time_series_antic$plot[[2]]
#ggsave("antic_7_plot.png", plot = antic_7_plot, width = 15, height = 7, path = here("figures"))
#ggsave("antic_20_plot.png", plot = antic_20_plot, width = 15, height = 7, path = here("figures"))


```



For models, we want one data point per baby per trial to use

each row from raw data is 1/60th of a second (60 Hz), approx.

Play around and plot vocab score as well - get rid of distractor, and have mono-high, mono-low (median split for visualization) * check that medians are similar amongst groups

```{r models, echo = FALSE}


model_data_3 <- make_time_window_data(data_eyetracking_clean,
                                      aois = "target",
                                      predictor_columns = c("trial_num", "language", "age_group", "total_vocab_prod", "trial_type")) 

model_pre_7_data_3 <- model_data_3 %>%
  filter(trial_type == "pre-switch") %>%
  filter(age_group == "7 months") %>%
  filter(AOI == "target")


model_pre_7_3 <- glmer(Prop ~ language * trial_num + (1 | recording_name), data = model_pre_7_data_3, family = "binomial") #failed to converge when random slope by time_scaled added

summary(model_pre_7_3)

model_post_7_data_3 <- model_data_3 %>%
  filter(trial_type == "post-switch") %>%
  filter(age_group == "7 months") %>%
  filter(AOI == "target")


model_post_7_3 <- glmer(Prop ~ language * trial_num + (1 | recording_name), data = model_post_7_data_3, family = "binomial") #failed to converge when random slope by time_scaled added

summary(model_post_7_3)

model_data_3 %>% 
  group_by(trial_num, trial_type, language, age_group) %>%
  summarize(means = mean(Prop, na.rm = TRUE))

## this data keeps binned timestamps -- question: the "AOI" column now has target and distractor stacked on top of one another. Not sure if we should be excluding distractor?
model_data <- data_time_series_antic %>%
  mutate(language_c = ifelse(language == "Monolinguals", -.5, .5)) %>% # sum-code and centre predictors 
  mutate(language_c = as.numeric(scale(language_c, center = TRUE, scale = FALSE))) %>% #  sum-code and centre predictors 
  mutate(trial_type_c = ifelse(trial_type == "pre-switch", -.5, .5)) %>%
  mutate(trial_type_c = as.numeric(scale(trial_type_c, center = TRUE, scale = FALSE))) %>%
  mutate(time_scaled = Time / 1000) #rescale time to help with large eigenvalue thing as done here: https://bit.ly/2O3tQne 



# this data keeps continuous timestamps and uses the count of TRUES in the "target" column for the DV:
model_data_2 <- data_eyetracking_clean %>%
  mutate(language_c = ifelse(language == "Monolinguals", -.5, .5)) %>% # sum-code and centre predictors 
  mutate(language_c = as.numeric(scale(language_c, center = TRUE, scale = FALSE))) %>% #  sum-code and centre predictors 
  mutate(trial_type_c = ifelse(trial_type == "pre-switch", -.5, .5)) %>%
  mutate(trial_type_c = as.numeric(scale(trial_type_c, center = TRUE, scale = FALSE))) %>%
  mutate(time_scaled = trial_from_zero / 1000)
  
###----------------------------------------------------------------------PRE-SWITCH 7-------------------------------------------------------------  
  
model_pre_7_data <- model_data %>%
  filter(trial_type == "pre-switch") %>%
  filter(age_group == "7 months") %>%
  filter(AOI == "target")


model_pre_7 <- glmer(Prop ~ language * trial_num + (1 | recording_name), data = model_pre_7_data, family = "binomial") #failed to converge when random slope by time_scaled added

summary(model_pre_7)

plot(model_pre_7) # question: is this problematic?


model_pre_7_data_2 <- model_data_2 %>%
  filter(trial_type == "pre-switch") %>%
  filter(age_group == "7 months")


model_pre_7_2 <- glmer(target ~ language * time_scaled + (1 | recording_name), data = model_pre_7_data_2, family = "binomial")

summary(model_pre_7_2)
plot(model_pre_7_2) # I have no idea how to interpret these


###----------------------------------------------------------------------POST-SWITCH 7-------------------------------------------------------------  

model_post_7_data <- model_data %>%
  filter(trial_type == "post-switch") %>%
  filter(age_group == "7 months") %>%
  filter(AOI == "target")


model_post_7 <- glmer(Prop ~ language * time_scaled + (1 | recording_name), data = model_post_7_data, family = "binomial")

summary(model_post_7)


model_post_7_data$prediction <- predict(model_post_7, model_post_7_data)

# in logit space...
ggplot(model_post_7_data, aes(x=time_scaled, y=prediction, color=language)) +
                            stat_summary(fun.y='mean', geom='line')


###----------------------------------------------------------------------PRE-SWITCH 20-------------------------------------------------------------  
  
model_pre_20_data <- model_data %>%
  filter(trial_type == "pre-switch") %>%
  filter(age_group == "20 months")%>%
  filter(AOI == "target") %>%
  filter(trial_num != 1)


model_pre_20 <- glmer(Prop ~ language * (ot1 + ot2 + ot3) + (1 | recording_name), data = model_pre_20_data, family = "binomial")

summary(model_pre_20)

model_pre_20_2 <- lmer(Elog ~ language * (ot1 + ot2 + ot3) + (1 | recording_name) + (1 | trial_num), data = model_pre_20_data, REML = FALSE)

summary(model_pre_20_2)


###----------------------------------------------------------------------POST-SWITCH 20-------------------------------------------------------------  

model_post_20_data <- model_data %>%
  filter(trial_type == "post-switch") %>%
  filter(age_group == "20 months")

model_post_20 <- glmer(Prop ~ language * time_scaled + (1 | recording_name), data = model_post_20_data, family = "binomial")

summary(model_post_20)


```


```{r anovas, echo = FALSE}

agg_subjects <- data_eyetracking_clean %>%
  group_by(recording_name, age_group, language, trial_type) %>%
  summarize(prop_target = mean(target, na.rm = TRUE)) %>% #this includes all looks though, not just target vs distractor
  ungroup()

ggplot(agg_subjects, aes(x = language, y = prop_target, color = language))  +
  geom_point(position = position_jitter(.3)) +
  facet_grid(age_group ~ fct_rev(trial_type))
```


